require("dotenv").config();
const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// -------------------
//  MongoDB Connection
// -------------------
const mongoUri = process.env.MONGODB_URI;
if (!mongoUri) {
  console.error("❌ MONGODB_URI is not set in .env");
  process.exit(1);
}

mongoose
  .connect(mongoUri)
  .then(() => console.log("✅ Connected to MongoDB Atlas"))
  .catch((err) => {
    console.error("❌ MongoDB connection error:", err);
    process.exit(1);
  });

// -------------------
//  Schemas & Models
// -------------------

// Users: minimal (id + name only)
const userSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true },
    name: { type: String, required: true }
  },
  { collection: "users" }
);
const User = mongoose.model("User", userSchema);

// Sellers
const sellerSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true },
    name: String,
    type: String, // "farmer" | "artisan"
    description: String,
    location: String,
    image: String,
    contactEmail: String,
    contactPhone: String,
    rating: Number,
    totalSales: Number
  },
  { collection: "sellers" }
);
const Seller = mongoose.model("Seller", sellerSchema);

// Products
const productSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true }, // "p1", "p2", autogenerated for new ones
    name: String,
    price: Number,
    category: String,
    image: String,
    description: String,
    sellerId: String,   // "s1", "s2"
    sellerName: String, // redundant but used by frontend
    stock: Number,
    rating: Number
  },
  { collection: "products" }
);
const Product = mongoose.model("Product", productSchema);

// Reviews
const reviewSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true }, // "r1", "r2", ...
    productId: String,   // "p1", "p2"
    customerId: String,  // "u1", "u2", ...
    customerName: String,
    rating: Number,
    comment: String,
    date: String
  },
  { collection: "reviews" }
);
const Review = mongoose.model("Review", reviewSchema);

// Orders
const orderSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true }, // "o1", "o2", ...
    customerId: String,
    customerName: String,
    items: [
      {
        productId: String,
        productName: String,
        quantity: Number,
        price: Number
      }
    ],
    total: Number,
    status: String, // "Pending" | "Confirmed" | "On Delivery" | "Received"
    date: String,
    shippingAddress: String
  },
  { collection: "orders" }
);
const Order = mongoose.model("Order", orderSchema);

// CartItems
const cartItemSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true }, // "c1", "c2", ...
    userId: String,     // "u1", "u2", ...
    productId: String,  // "p1", ...
    name: String,
    price: Number,
    image: String,
    sellerName: String,
    quantity: Number,
    stock: Number
  },
  { collection: "cartItems" }
);
const CartItem = mongoose.model("CartItem", cartItemSchema);

// -------------------
//  Helper: ID generator
// -------------------
function generateId(prefix) {
  return prefix + Date.now().toString();
}

// -------------------
//  Routes
// -------------------

// Simple health check
app.get("/", (req, res) => {
  res.json({ status: "ok", message: "Marketplace API is running" });
});

// ----- PRODUCTS -----

// Get all products (for product listing, homepage, etc.)
app.get("/api/products", async (req, res) => {
  try {
    const products = await Product.find().lean();
    res.json(products);
  } catch (err) {
    console.error("Error fetching products:", err);
    res.status(500).json({ error: "Failed to fetch products" });
  }
});

// Get a single product by custom id (e.g., "p1")
app.get("/api/products/:id", async (req, res) => {
  try {
    const product = await Product.findOne({ id: req.params.id }).lean();
    if (!product) return res.status(404).json({ error: "Product not found" });
    res.json(product);
  } catch (err) {
    console.error("Error fetching product:", err);
    res.status(500).json({ error: "Failed to fetch product" });
  }
});

// Create a new product (seller adding a product, backend generates id)
app.post("/api/products", async (req, res) => {
  try {
    const newId = generateId("p"); // e.g. "p1732050000000"
    const product = await Product.create({
      ...req.body,
      id: newId
    });
    res.status(201).json(product);
  } catch (err) {
    console.error("Error creating product:", err);
    res.status(500).json({ error: "Failed to create product" });
  }
});

// Optional: update product by custom id
app.patch("/api/products/:id", async (req, res) => {
  try {
    const updated = await Product.findOneAndUpdate(
      { id: req.params.id },
      req.body,
      { new: true }
    ).lean();
    if (!updated) return res.status(404).json({ error: "Product not found" });
    res.json(updated);
  } catch (err) {
    console.error("Error updating product:", err);
    res.status(500).json({ error: "Failed to update product" });
  }
});

// Optional: delete product by custom id
app.delete("/api/products/:id", async (req, res) => {
  try {
    const deleted = await Product.findOneAndDelete({ id: req.params.id }).lean();
    if (!deleted) return res.status(404).json({ error: "Product not found" });
    res.json({ message: "Product deleted" });
  } catch (err) {
    console.error("Error deleting product:", err);
    res.status(500).json({ error: "Failed to delete product" });
  }
});

// ----- SELLERS -----

// Get all sellers
app.get("/api/sellers", async (req, res) => {
  try {
    const sellers = await Seller.find().lean();
    res.json(sellers);
  } catch (err) {
    console.error("Error fetching sellers:", err);
    res.status(500).json({ error: "Failed to fetch sellers" });
  }
});

// Get one seller by id ("s1")
app.get("/api/sellers/:id", async (req, res) => {
  try {
    const seller = await Seller.findOne({ id: req.params.id }).lean();
    if (!seller) return res.status(404).json({ error: "Seller not found" });
    res.json(seller);
  } catch (err) {
    console.error("Error fetching seller:", err);
    res.status(500).json({ error: "Failed to fetch seller" });
  }
});

// Products by seller (for seller profile / dashboard)
app.get("/api/sellers/:id/products", async (req, res) => {
  try {
    const products = await Product.find({ sellerId: req.params.id }).lean();
    res.json(products);
  } catch (err) {
    console.error("Error fetching seller products:", err);
    res.status(500).json({ error: "Failed to fetch seller products" });
  }
});

// ----- REVIEWS -----

// Reviews for a product
app.get("/api/products/:id/reviews", async (req, res) => {
  try {
    const reviews = await Review.find({ productId: req.params.id }).lean();
    res.json(reviews);
  } catch (err) {
    console.error("Error fetching reviews:", err);
    res.status(500).json({ error: "Failed to fetch reviews" });
  }
});

// Create a review for a product
app.post("/api/products/:id/reviews", async (req, res) => {
  try {
    const newId = generateId("r");
    const review = await Review.create({
      ...req.body,
      id: newId,
      productId: req.params.id
    });
    res.status(201).json(review);
  } catch (err) {
    console.error("Error creating review:", err);
    res.status(500).json({ error: "Failed to create review" });
  }
});

// ----- ORDERS -----

// Get all orders for a user
app.get("/api/users/:userId/orders", async (req, res) => {
  try {
    const orders = await Order.find({ customerId: req.params.userId }).lean();
    res.json(orders);
  } catch (err) {
    console.error("Error fetching orders:", err);
    res.status(500).json({ error: "Failed to fetch orders" });
  }
});

// Create a new order (e.g., from checkout)
app.post("/api/users/:userId/orders", async (req, res) => {
  try {
    const newId = generateId("o");
    const order = await Order.create({
      ...req.body,
      id: newId,
      customerId: req.params.userId
    });
    res.status(201).json(order);
  } catch (err) {
    console.error("Error creating order:", err);
    res.status(500).json({ error: "Failed to create order" });
  }
});

// ----- CART ITEMS -----

// Get cart items for a user
app.get("/api/users/:userId/cart", async (req, res) => {
  try {
    const items = await CartItem.find({ userId: req.params.userId }).lean();
    res.json(items);
  } catch (err) {
    console.error("Error fetching cart items:", err);
    res.status(500).json({ error: "Failed to fetch cart items" });
  }
});

// Add item to cart for a user
app.post("/api/users/:userId/cart", async (req, res) => {
  try {
    const newId = generateId("c");
    const item = await CartItem.create({
      ...req.body,
      id: newId,
      userId: req.params.userId
    });
    res.status(201).json(item);
  } catch (err) {
    console.error("Error adding cart item:", err);
    res.status(500).json({ error: "Failed to add cart item" });
  }
});

// Update quantity of a cart item by custom cart id ("c1")
app.patch("/api/cart/:cartId", async (req, res) => {
  try {
    const updated = await CartItem.findOneAndUpdate(
      { id: req.params.cartId },
      req.body,
      { new: true }
    ).lean();
    if (!updated) return res.status(404).json({ error: "Cart item not found" });
    res.json(updated);
  } catch (err) {
    console.error("Error updating cart item:", err);
    res.status(500).json({ error: "Failed to update cart item" });
  }
});

// Remove a cart item
app.delete("/api/cart/:cartId", async (req, res) => {
  try {
    const deleted = await CartItem.findOneAndDelete({ id: req.params.cartId }).lean();
    if (!deleted) return res.status(404).json({ error: "Cart item not found" });
    res.json({ message: "Cart item removed" });
  } catch (err) {
    console.error("Error deleting cart item:", err);
    res.status(500).json({ error: "Failed to delete cart item" });
  }
});

// -------------------
//  Start server
// -------------------
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`🚀 Server running on http://localhost:${port}`);
});
